service: slack-chatbot

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  stage: demo
  region: eu-central-1
  memorySize: 256
  timeout: 5
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  environment:
    SLACK_VERIFICATION_TOKEN: ${file(sls-props.yml):slack.verification_token}
    S3_BUCKET: ${file(sls-props.yml):s3.bucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectVersion
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

package:
  artifact: target/${self:service}.jar

functions:
  command:
    handler: de.serverlessbuch.slack.command.CommandHandler
    events:
      - http:
          path: /command
          method: POST
  install:
    handler: de.serverlessbuch.slack.InstallHandler
    environment:
      SLACK_CLIENT_ID: ${file(sls-props.yml):slack.client_id}
    events:
      - http: GET install
  authorized:
    handler: de.serverlessbuch.slack.AuthorizedHandler
    environment:
      SLACK_CLIENT_ID: ${file(sls-props.yml):slack.client_id}
      SLACK_CLIENT_SECRET: ${file(sls-props.yml):slack.client_secret}
    events:
      - http: GET authorized
  event:
    handler: de.serverlessbuch.slack.event.EventHandler
    events:
      - http: POST event
